stages:
  - test
  - security

# --- VARIABLES GLOBALES ---
variables:
  GITLAB_ADVANCED_SAST_ENABLED: "true"


include:
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.v2.gitlab-ci.yml

