stages:
  - test

include:
  # 1. SAST (Static Application Security Testing)
  # Usamos el componente y le pasamos las exclusiones AQUÍ DIRECTAMENTE.
  - component: gitlab.com/components/sast/sast@main
  - component: gitlab.com/components/sast/iac-sast@main
    inputs:
      excluded_paths: "docs, **/*.md, test, spec, tmp"
      GITLAB_ADVANCED_SAST_ANALYZER: "true"
      # search_max_depth: 20

  # 2. Secret Detection
  - component: gitlab.com/components/secret-detection/secret-detection@main

  # 3. SCA (Dependency Scanning)
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml

# --- CONFIGURACIONES ADICIONALES ---

# Secret Detection sí permite esta configuración global para el historial
secret_detection:
  variables:
    SECRET_DETECTION_HISTORIC_SCAN: "true"

# ¡IMPORTANTE! 
# He borrado el bloque 'sast:' que había aquí abajo porque causaba el error.
# La configuración de SAST ahora está arriba, dentro del 'component'.